name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: ${{ secrets.RUN_REGION }}
  SERVICE_NAME: ${{ secrets.RUN_SERVICE_NAME }}
  OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
  OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
  OAUTH_AUTH_URL: ${{ secrets.OAUTH_AUTH_URL }}
  OAUTH_TOKEN_URL: ${{ secrets.OAUTH_TOKEN_URL }}
  OAUTH_REDIRECT_URI: ${{ secrets.OAUTH_REDIRECT_URI }}
  OAUTH_APP_LAUNCH_URI: ${{ secrets.OAUTH_APP_LAUNCH_URI }}
  OAUTH_COMPLETE_URI: ${{ secrets.OAUTH_COMPLETE_URI }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "286.0.0"
          service_account_email: ${{ secrets.RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated \
            --set-env-vars="OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID},OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET},OAUTH_AUTH_URL=${OAUTH_AUTH_URL},OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL},OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI},OAUTH_APP_LAUNCH_URI=${OAUTH_APP_LAUNCH_URI},OAUTH_COMPLETE_URI=${OAUTH_COMPLETE_URI}"
